# Custom pose training dataset (synthetic + camera collected)
path: C:\customFolder\ouRunTe\my_digital_twin\data
train: train/images
val: val/images

kpt_shape: [17, 3]
flip_idx: [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15]

names:
  0: person
